name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy index.html to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Starting Deployment..."

          # Ensure Apache2 installed
          sudo apt update -y
          sudo apt install apache2 -y
          sudo systemctl start apache2
          sudo systemctl enable apache2

          # Copy website file
          sudo rm -f /var/www/html/index.html
          sudo cp $GITHUB_WORKSPACE/index.html /var/www/html/index.html

          sudo chown www-data:www-data /var/www/html/index.html
          sudo systemctl restart apache2

          echo "Deployment Completed Successfully!"
